// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Residuos_MODEL.Models;

public partial class Notificaco
{
    public int NotificacaoId { get; set; }

    public string Mensagem { get; set; }

    public DateTime DataEnvio { get; set; }

    public int ResidenciaEstabelecimentoId { get; set; }

    public virtual ResidenciasEstabelecimento ResidenciaEstabelecimento { get; set; }
}