// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Residuos_MODEL.Models;

public partial class PontosColetum
{
    public int PontoColetaId { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public int TipoResiduoId { get; set; }

    public virtual TiposResiduo TipoResiduo { get; set; }
}