// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Residuos_MODEL.Models;

public partial class ResidenciasEstabelecimento
{
    public int ResidenciaEstabelecimentoId { get; set; }

    public int TipoEstabelecimentoId { get; set; }

    public string NomeResidencia { get; set; }

    public virtual ICollection<Notificaco> Notificacos { get; set; } = new List<Notificaco>();

    public virtual TiposEstabelecimento TipoEstabelecimento { get; set; }
}