// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Residuos_MODEL.Models;

public partial class TiposResiduo
{
    public int TipoResiduoId { get; set; }

    public string Resíduo { get; set; }

    public string FotoResiduo { get; set; }
            
    public virtual ICollection<CalendarioColetum> CalendarioColeta { get; set; } = new List<CalendarioColetum>();

    public virtual ICollection<PontosColetum> PontosColeta { get; set; } = new List<PontosColetum>();
}