// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Residuos_MODEL.Models;

public partial class TiposEstabelecimento
{
    public int TipoEstabelecimentoId { get; set; }

    public virtual ICollection<ResidenciasEstabelecimento> ResidenciasEstabelecimentos { get; set; } = new List<ResidenciasEstabelecimento>();
}