// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Residuos_MODEL.Models;

public partial class Token
{
    public int Id { get; set; }

    public string TokenValue { get; set; }

    public DateTime? CreatedDate { get; set; }
}